package com.nikol.ui.theme.color
import androidx.compose.ui.graphics.Color

val greenPrimaryLight = Color(0xFF306A42)
val greenOnPrimaryLight = Color(0xFFFFFFFF)
val greenPrimaryContainerLight = Color(0xFFB3F1BF)
val greenOnPrimaryContainerLight = Color(0xFF15512C)
val greenSecondaryLight = Color(0xFF506352)
val greenOnSecondaryLight = Color(0xFFFFFFFF)
val greenSecondaryContainerLight = Color(0xFFD2E8D3)
val greenOnSecondaryContainerLight = Color(0xFF384B3C)
val greenTertiaryLight = Color(0xFF3A656E)
val greenOnTertiaryLight = Color(0xFFFFFFFF)
val greenTertiaryContainerLight = Color(0xFFBEEAF5)
val greenOnTertiaryContainerLight = Color(0xFF204D56)
val greenErrorLight = Color(0xFFBA1A1A)
val greenOnErrorLight = Color(0xFFFFFFFF)
val greenErrorContainerLight = Color(0xFFFFDAD6)
val greenOnErrorContainerLight = Color(0xFF93000A)
val greenBackgroundLight = Color(0xFFF6FBF3)
val greenOnBackgroundLight = Color(0xFF181D18)
val greenSurfaceLight = Color(0xFFF6FBF3)
val greenOnSurfaceLight = Color(0xFF181D18)
val greenSurfaceVariantLight = Color(0xFFDDE5DA)
val greenOnSurfaceVariantLight = Color(0xFF414941)
val greenOutlineLight = Color(0xFF717971)
val greenOutlineVariantLight = Color(0xFFC1C9BF)
val greenScrimLight = Color(0xFF000000)
val greenInverseSurfaceLight = Color(0xFF2D322D)
val greenInverseOnSurfaceLight = Color(0xFFEEF2EA)
val greenInversePrimaryLight = Color(0xFF98D5A4)
val greenSurfaceDimLight = Color(0xFFD7DBD4)
val greenSurfaceBrightLight = Color(0xFFF6FBF3)
val greenSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val greenSurfaceContainerLowLight = Color(0xFFF0F5ED)
val greenSurfaceContainerLight = Color(0xFFEBEFE7)
val greenSurfaceContainerHighLight = Color(0xFFE5EAE2)
val greenSurfaceContainerHighestLight = Color(0xFFDFE4DC)




val greenPrimaryDark = Color(0xFF98D5A4)
val greenOnPrimaryDark = Color(0xFF00391A)
val greenPrimaryContainerDark = Color(0xFF15512C)
val greenOnPrimaryContainerDark = Color(0xFFB3F1BF)
val greenSecondaryDark = Color(0xFFB7CCB8)
val greenOnSecondaryDark = Color(0xFF223526)
val greenSecondaryContainerDark = Color(0xFF384B3C)
val greenOnSecondaryContainerDark = Color(0xFFD2E8D3)
val greenTertiaryDark = Color(0xFFA2CED9)
val greenOnTertiaryDark = Color(0xFF01363F)
val greenTertiaryContainerDark = Color(0xFF204D56)
val greenOnTertiaryContainerDark = Color(0xFFBEEAF5)
val greenErrorDark = Color(0xFFFFB4AB)
val greenOnErrorDark = Color(0xFF690005)
val greenErrorContainerDark = Color(0xFF93000A)
val greenOnErrorContainerDark = Color(0xFFFFDAD6)
val greenBackgroundDark = Color(0xFF101510)
val greenOnBackgroundDark = Color(0xFFDFE4DC)
val greenSurfaceDark = Color(0xFF101510)
val greenOnSurfaceDark = Color(0xFFDFE4DC)
val greenSurfaceVariantDark = Color(0xFF414941)
val greenOnSurfaceVariantDark = Color(0xFFC1C9BF)
val greenOutlineDark = Color(0xFF8B938A)
val greenOutlineVariantDark = Color(0xFF414941)
val greenScrimDark = Color(0xFF000000)
val greenInverseSurfaceDark = Color(0xFFDFE4DC)
val greenInverseOnSurfaceDark = Color(0xFF2D322D)
val greenInversePrimaryDark = Color(0xFF306A42)
val greenSurfaceDimDark = Color(0xFF101510)
val greenSurfaceBrightDark = Color(0xFF353A35)
val greenSurfaceContainerLowestDark = Color(0xFF0B0F0B)
val greenSurfaceContainerLowDark = Color(0xFF181D18)
val greenSurfaceContainerDark = Color(0xFF1C211C)
val greenSurfaceContainerHighDark = Color(0xFF262B26)
val greenSurfaceContainerHighestDark = Color(0xFF313631)